-- MySQL Script generated by MySQL Workbench
-- Thu Nov  1 21:57:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema controle_financeiro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controle_financeiro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controle_financeiro` DEFAULT CHARACTER SET utf8 ;
USE `controle_financeiro` ;

-- -----------------------------------------------------
-- Table `controle_financeiro`.`tipoperacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_financeiro`.`tipoperacao` (
  `codop` INT NOT NULL AUTO_INCREMENT,
  `descop` VARCHAR(45) NULL,
  PRIMARY KEY (`codop`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_financeiro`.`grupoconta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_financeiro`.`grupoconta` (
  `codgrupo` INT NOT NULL AUTO_INCREMENT,
  `nomegrupo` VARCHAR(45) NULL,
  PRIMARY KEY (`codgrupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_financeiro`.`tipoconta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_financeiro`.`tipoconta` (
  `codconta` INT NOT NULL AUTO_INCREMENT,
  `nomeconta` VARCHAR(45) NULL,
  `tipocontacol` VARCHAR(45) NULL,
  `codop` INT NOT NULL,
  `codgrupo` INT NOT NULL,
  PRIMARY KEY (`codconta`),
  INDEX `idx_tipoconta_tipoperacao` (`codop` ASC),
  INDEX `idx_tipoconta_grupoconta` (`codgrupo` ASC),
  CONSTRAINT `fk_tipoconta_tipoperacao`
    FOREIGN KEY (`codop`)
    REFERENCES `controle_financeiro`.`tipoperacao` (`codop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipoconta_grupoconta`
    FOREIGN KEY (`codgrupo`)
    REFERENCES `controle_financeiro`.`grupoconta` (`codgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_financeiro`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_financeiro`.`cliente` (
  `codcliente` INT NOT NULL AUTO_INCREMENT,
  `nomecliente` VARCHAR(150) NULL,
  `cpf` VARCHAR(45) NULL,
  PRIMARY KEY (`codcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_financeiro`.`banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_financeiro`.`banco` (
  `codbanco` INT NOT NULL AUTO_INCREMENT,
  `nrobanco` VARCHAR(10) NULL,
  `razaosocial` VARCHAR(150) NULL,
  `nomefantasia` VARCHAR(150) NULL,
  `codcliente` INT NOT NULL,
  PRIMARY KEY (`codbanco`),
  INDEX `idx_banco_cliente` (`codcliente` ASC),
  CONSTRAINT `fk_banco_cliente`
    FOREIGN KEY (`codcliente`)
    REFERENCES `controle_financeiro`.`cliente` (`codcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_financeiro`.`contabanco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_financeiro`.`contabanco` (
  `idconta` INT NOT NULL AUTO_INCREMENT,
  `nroagencia` VARCHAR(150) NULL,
  `natconta` VARCHAR(20) NULL,
  `nroconta` VARCHAR(45) NULL,
  `tipooperacao` VARCHAR(11) NULL,
  `codbanco` INT NOT NULL,
  PRIMARY KEY (`idconta`),
  INDEX `idx_contabanco_banco` (`codbanco` ASC),
  CONSTRAINT `fk_contabanco_banco`
    FOREIGN KEY (`codbanco`)
    REFERENCES `controle_financeiro`.`banco` (`codbanco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_financeiro`.`movimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_financeiro`.`movimentacao` (
  `codmov` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `valor` DOUBLE NULL,
  `datamov` DATE NOT NULL,
  `codconta` INT NOT NULL,
  `idconta` INT NOT NULL,
  PRIMARY KEY (`codmov`),
  INDEX `idx_movimentacao_tipoconta` (`codconta` ASC),
  INDEX `idx_movimentacao_contabanco` (`idconta` ASC),
  CONSTRAINT `fk_movimentacao_tipoconta`
    FOREIGN KEY (`codconta`)
    REFERENCES `controle_financeiro`.`tipoconta` (`codconta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimentacao_contabanco`
    FOREIGN KEY (`idconta`)
    REFERENCES `controle_financeiro`.`contabanco` (`idconta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_financeiro`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_financeiro`.`usuario` (
  `codusuario` INT NOT NULL,
  `nomeusuario` VARCHAR(10) NULL,
  PRIMARY KEY (`codusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_financeiro`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_financeiro`.`modulo` (
  `codmodulo` INT NOT NULL AUTO_INCREMENT,
  `desmodulo` VARCHAR(20) NULL,
  `urlmodulo` VARCHAR(500) NULL,
  PRIMARY KEY (`codmodulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_financeiro`.`usuario_modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_financeiro`.`usuario_modulo` (
  `codusuario` INT NOT NULL,
  `codmodulo` INT NOT NULL,
  PRIMARY KEY (`codusuario`, `codmodulo`),
  INDEX `idx_usuario_modulo_modulo` (`codmodulo` ASC),
  INDEX `idx_usuario_modulo_usuario` (`codusuario` ASC),
  CONSTRAINT `fk_usuario_modulo_usuario`
    FOREIGN KEY (`codusuario`)
    REFERENCES `controle_financeiro`.`usuario` (`codusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_modulo_modulo`
    FOREIGN KEY (`codmodulo`)
    REFERENCES `controle_financeiro`.`modulo` (`codmodulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
